## Homework 4

<!--
Remember you can use the example4.Rmd or other files to find examples
of the codes you'll need to use to complete this assignment. I strongly
urge you to copy and paste relevant code that you know works from my
examples or instructions and then edit that code so you're working
with the appropriate variables for the homework.
-->

<!--
Set the working directory.
No Rchunk is needed to accomplish this.
-->

<!--
Read in the homework4.csv data. For each of the following steps you
should preface your R commands with some plain English explanation.
This is where I read in the data.
-->
```{r}
dat<-read.csv("homework4.csv")
```

Now, I must check the structure of the data.
<!--
Check the structure of the data.
-->
```{r}
str(dat)
```

Here I created a table that shows how many people are in each catagory.
<!--
Create a table that shows how many people fell into each category.
-->
mytable<-table(dat$agreement,dat$condition)

```{r}
table(dat$agreement, dat$condition)
```

<!--
Perform a chi-square test to determine whether or not the experimental
conditions and agreement with a statement are independent or related.
Also, interpret the results of your test and provide a a statistical
statement that supports your interpretation. As there's no way to
insert the chi-square symbol, you can just use chi-square instead
(see example4.Rmd).
-->
Here I performed a chi-square test to determine if the agreements and conditions are related.
chisq.test(dat$agreement, dat$condition)

According the the results of the chi-test, the experiment didn't affect many of the people.
